#from http://mutelight.org/articles/practical-tmux
# C-b is not acceptable — Vim uses it
set-option -g prefix `
bind-key C-a last-window

# Make `` send a `
bind-key ` send-keys `

# Start numbering at 1
# stupid
# set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Set status bar
#set -g status-bg black
#set -g status-fg white
set -g status-left ""
set -g status-right ""

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Activity monitoring
#setw -g monitor-activity on
# set -g visual-activity on

# Example of using a shell command in the status line
#set -g status-right "#[fg=yellow]#(uptime | cut -d ',' -f 2-)"

# Highlight active window
#set-window-option -g window-status-current-bg white

# Sane split binding
unbind %
bind | split-window -h -c '#{pane_current_path}'
bind _ split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

# Now search like screen
bind '"' choose-window

#switch prefix key
bind-key P set-option -g prefix C-a
bind-key O set-option -g prefix `

#vi
set-window-option -g mode-keys vi

# Update default binding of `Enter` to also use copy-pipe
#unbind -T vi-copy Enter
#bind-key -T vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"

#display
set -g display-panes-time 5000

# pane movement
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"

# Moving windows
bind-key = select-pane -t :.+
bind-key - select-pane -t :.-

# Break a pane away and create a new one
bind-key N command-prompt -p "h or v split:" "break-pane -d \; split-window -'%%'"

set -g default-shell $SHELL
#set -g default-command "reattach-to-user-namespace -l ${SHELL}"

# Use system clipboard
#set -g default-command "${SHELL}"

# Enable mouse
set -g mouse on

bind -T copy-mode-vi Space send -X begin-selection
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
